### ISSUE TITLE
Support for Packaging Loader and BPF program

### ISSUE THREAD

**Issue by lgadban** [solo-io/bumblebee#41]
The current BumbleBee workflow is:

1. Develop BPF programs/probes
2. Build and package BPF program in OCI image via `bee build` 
3. Run BPF programs via `bee run`

So, in order to run your BPF programs, the `bee` CLI must be present on any system you wish to run them on.

To make the entire process portable, we can package the `bee` runner/loader along with the built BPF programs in a container to allow it to run anywhere without prior work necessary to e.g. install the `bee` CLI.

cc: @aantn -- thanks for the suggestion!

**Comment by aantn** [comment]
I love this. To clarify, deploying the probe will be as simple as deploying the docker container with appropriate permissions/capabilities, right?

**Comment by lgadban** [comment]
Yes, exactly!

**Comment by aantn** [comment]
Wonderful, as soon as this is ready I have a very cool use case in mind :)
