### ISSUE TITLE
Bumblebee build fails

### ISSUE THREAD

**Issue by pico-martin** [solo-io/bumblebee#69]
### Version

Fails during build

### Linux Version

Ubuntu 20

### Describe the bug

I cloned the code from github and ran 'go install ./bee

git clone https://github.com/solo-io/bumblebee.git
sudo go install ./bee

The build failed with the error:
build github.com/solo-io/bumblebee/bee: cannot load embed: malformed module path "embed": missing dot in first path element
[issue.txt](https://github.com/solo-io/bumblebee/files/8238128/issue.txt)

### Steps to reproduce the bug

git clone https://github.com/solo-io/bumblebee.git
sudo go install ./bee

### Expected Behavior

That I could use the bee command

**Comment by yuval-k** [comment]
what's you go version? `embed` is go 1.16+ feature.

**Comment by yuval-k** [comment]
Closing as answered. Using go 1.16+ should solve this issue. Please re-open if needed.
